project_id = "mczagaaiyzbhjvtrojia"

[functions.chat]
verify_jwt = true

[functions.create-payment]
verify_jwt = false

[functions.send-vanity-quote]
verify_jwt = false

[functions.send-quote-request]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
